# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kill_time/project/optimization

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kill_time/project/optimization

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kill_time/project/optimization/CMakeFiles /home/kill_time/project/optimization//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kill_time/project/optimization/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named optimization

# Build rule for target.
optimization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 optimization
.PHONY : optimization

# fast build rule for target.
optimization/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/build
.PHONY : optimization/fast

analisis/analis.o: analisis/analis.cpp.o
.PHONY : analisis/analis.o

# target to build an object file
analisis/analis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/analisis/analis.cpp.o
.PHONY : analisis/analis.cpp.o

analisis/analis.i: analisis/analis.cpp.i
.PHONY : analisis/analis.i

# target to preprocess a source file
analisis/analis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/analisis/analis.cpp.i
.PHONY : analisis/analis.cpp.i

analisis/analis.s: analisis/analis.cpp.s
.PHONY : analisis/analis.s

# target to generate assembly for a file
analisis/analis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/analisis/analis.cpp.s
.PHONY : analisis/analis.cpp.s

controller/input_controller/parsers.o: controller/input_controller/parsers.cpp.o
.PHONY : controller/input_controller/parsers.o

# target to build an object file
controller/input_controller/parsers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/input_controller/parsers.cpp.o
.PHONY : controller/input_controller/parsers.cpp.o

controller/input_controller/parsers.i: controller/input_controller/parsers.cpp.i
.PHONY : controller/input_controller/parsers.i

# target to preprocess a source file
controller/input_controller/parsers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/input_controller/parsers.cpp.i
.PHONY : controller/input_controller/parsers.cpp.i

controller/input_controller/parsers.s: controller/input_controller/parsers.cpp.s
.PHONY : controller/input_controller/parsers.s

# target to generate assembly for a file
controller/input_controller/parsers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/input_controller/parsers.cpp.s
.PHONY : controller/input_controller/parsers.cpp.s

controller/logger_controller/handler.o: controller/logger_controller/handler.cpp.o
.PHONY : controller/logger_controller/handler.o

# target to build an object file
controller/logger_controller/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/handler.cpp.o
.PHONY : controller/logger_controller/handler.cpp.o

controller/logger_controller/handler.i: controller/logger_controller/handler.cpp.i
.PHONY : controller/logger_controller/handler.i

# target to preprocess a source file
controller/logger_controller/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/handler.cpp.i
.PHONY : controller/logger_controller/handler.cpp.i

controller/logger_controller/handler.s: controller/logger_controller/handler.cpp.s
.PHONY : controller/logger_controller/handler.s

# target to generate assembly for a file
controller/logger_controller/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/handler.cpp.s
.PHONY : controller/logger_controller/handler.cpp.s

controller/logger_controller/interface.o: controller/logger_controller/interface.cpp.o
.PHONY : controller/logger_controller/interface.o

# target to build an object file
controller/logger_controller/interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/interface.cpp.o
.PHONY : controller/logger_controller/interface.cpp.o

controller/logger_controller/interface.i: controller/logger_controller/interface.cpp.i
.PHONY : controller/logger_controller/interface.i

# target to preprocess a source file
controller/logger_controller/interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/interface.cpp.i
.PHONY : controller/logger_controller/interface.cpp.i

controller/logger_controller/interface.s: controller/logger_controller/interface.cpp.s
.PHONY : controller/logger_controller/interface.s

# target to generate assembly for a file
controller/logger_controller/interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/interface.cpp.s
.PHONY : controller/logger_controller/interface.cpp.s

controller/logger_controller/logger.o: controller/logger_controller/logger.cpp.o
.PHONY : controller/logger_controller/logger.o

# target to build an object file
controller/logger_controller/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/logger.cpp.o
.PHONY : controller/logger_controller/logger.cpp.o

controller/logger_controller/logger.i: controller/logger_controller/logger.cpp.i
.PHONY : controller/logger_controller/logger.i

# target to preprocess a source file
controller/logger_controller/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/logger.cpp.i
.PHONY : controller/logger_controller/logger.cpp.i

controller/logger_controller/logger.s: controller/logger_controller/logger.cpp.s
.PHONY : controller/logger_controller/logger.s

# target to generate assembly for a file
controller/logger_controller/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/controller/logger_controller/logger.cpp.s
.PHONY : controller/logger_controller/logger.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimization.dir/build.make CMakeFiles/optimization.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... optimization"
	@echo "... analisis/analis.o"
	@echo "... analisis/analis.i"
	@echo "... analisis/analis.s"
	@echo "... controller/input_controller/parsers.o"
	@echo "... controller/input_controller/parsers.i"
	@echo "... controller/input_controller/parsers.s"
	@echo "... controller/logger_controller/handler.o"
	@echo "... controller/logger_controller/handler.i"
	@echo "... controller/logger_controller/handler.s"
	@echo "... controller/logger_controller/interface.o"
	@echo "... controller/logger_controller/interface.i"
	@echo "... controller/logger_controller/interface.s"
	@echo "... controller/logger_controller/logger.o"
	@echo "... controller/logger_controller/logger.i"
	@echo "... controller/logger_controller/logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

